"""Widget components for meetandread."""

from .main_widget import MeetAndReadWidget
from .icons import create_app_icon, create_recording_icon
from .tray_icon import TrayIconManager
from .theme import (
    ThemePalette,
    DARK_PALETTE,
    LIGHT_PALETTE,
    current_palette,
    is_dark_mode,
    panel_base_css,
    title_css,
    header_button_css,
    tab_widget_css,
    text_area_css,
    combo_box_css,
    action_button_css,
    list_widget_css,
    progress_bar_css,
    context_menu_css,
    dialog_css,
    badge_css,
    resize_grip_css,
    legend_overlay_css,
    detail_header_css,
    separator_css,
    info_label_css,
    status_label_css,
    splitter_css,
)

__all__ = [
    "MeetAndReadWidget",
    "create_app_icon",
    "create_recording_icon",
    "TrayIconManager",
    # Theme
    "ThemePalette",
    "DARK_PALETTE",
    "LIGHT_PALETTE",
    "current_palette",
    "is_dark_mode",
    "panel_base_css",
    "title_css",
    "header_button_css",
    "tab_widget_css",
    "text_area_css",
    "combo_box_css",
    "action_button_css",
    "list_widget_css",
    "progress_bar_css",
    "context_menu_css",
    "dialog_css",
    "badge_css",
    "resize_grip_css",
    "legend_overlay_css",
    "detail_header_css",
    "separator_css",
    "info_label_css",
    "status_label_css",
    "splitter_css",
]